<a href="https://colab.research.google.com/github/2303A51528/AIML-1528-/blob/main/assignment%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
array_1 = np.array([1,2,3,4,5])
print(array_1)
List_1 =[1,2,3,4,5]
List_2 =[6,7,8,9,10]
print(List_1)
print(List_1[2])
print(List_1[0])
x = 8
y = 0.59
z = "Nishi"
print (type(x))
print (type(y))
print (type(z))
print (type(List_1))

import numpy as np
array_1 =np.array([7,4,8,2])
array_2 =np.array([2,5,1,6])
result = array_1 * array_2
print(result)

import numpy as np
array1 = np.array([7,4,8,2])
array2 = np.array([9,5,3,6])
result = array1 / array2
print(result)

import numpy as np
array1 = np.array([7,4,8,2])
array2 = np.array([9,5,3,6])
result = array1 ** array2
print(result)

import numpy as np
array1 = np.array([7,4,8,2])
array2 = np.array([9,5,3,6])
result = array1 + array2
print("addition of 2 arrays:",result)

import numpy as np
array3 = np.array([0,np.pi/2,np.pi*3])
sinarray = np.sin(array3)
print (sinarray)

import numpy as np
array4 = np.array([0, np.e/2,np.e*3])
logarray = np.log(array4)
print (logarray)

import numpy as np
array5 = np.array([1,np.e,np.e**2,10])
log_array = np.log(array5)
print(log_array)


[1 2 3 4 5]
[1, 2, 3, 4, 5]
3
1
<class 'int'>
<class 'float'>
<class 'str'>
<class 'list'>
[14 20  8 12]
[0.77777778 0.8        2.66666667 0.33333333]
[40353607     1024      512       64]
addition of 2 arrays: [16  9 11  8]
[0.0000000e+00 1.0000000e+00 3.6739404e-16]
[      -inf 0.30685282 2.09861229]
[0.         1.         2.         2.30258509]


<ipython-input-1-73b622392c54>:48: RuntimeWarning: divide by zero encountered in log
  logarray = np.log(array4)
